#!/usr/bin/env bash

set -euo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
build_root="$repository_root/.build/distribution-build"
output_dir="$repository_root/.build/distribution"
staging_dir="$output_dir/staging"
cli_archive_name="capsled-macos-universal.tar.gz"
menu_archive_name="capsled-menu-bar-macos-universal.zip"
app_dir="$output_dir/CapsLED.app"
app_contents="$app_dir/Contents"
app_resources="$app_contents/Resources"
version="${CAPSLED_VERSION:-0.0.0}"
version="${version#v}"
build_version="${CAPSLED_BUILD_VERSION:-1}"

# These directories are entirely generated by this script. Clearing only these
# known paths prevents stale slices or checksums from entering a new release,
# while leaving ordinary SwiftPM build products and user files untouched.
rm -rf "$build_root" "$output_dir"
mkdir -p "$staging_dir"

swift build \
    --package-path "$repository_root" \
    --configuration release \
    --arch arm64 \
    --scratch-path "$build_root/arm64"

swift build \
    --package-path "$repository_root" \
    --configuration release \
    --arch x86_64 \
    --scratch-path "$build_root/x86_64"

lipo -create \
    "$build_root/arm64/arm64-apple-macosx/release/capsled" \
    "$build_root/x86_64/x86_64-apple-macosx/release/capsled" \
    -output "$staging_dir/capsled"
lipo "$staging_dir/capsled" -verify_arch arm64 x86_64

# The menu-bar target is a normal Swift executable during development. Release
# packaging wraps its two architecture slices in a standard LSUIElement app so
# users can launch CapsLED from Finder without installing or opening a terminal.
mkdir -p "$app_contents/MacOS" "$app_resources"
cp "$repository_root/Support/CapsLEDMenuBar-Info.plist" "$app_contents/Info.plist"
cp "$repository_root/LICENSE" "$app_resources/LICENSE"
/usr/libexec/PlistBuddy \
    -c "Set :CFBundleShortVersionString $version" \
    "$app_contents/Info.plist"
/usr/libexec/PlistBuddy \
    -c "Set :CFBundleVersion $build_version" \
    "$app_contents/Info.plist"
lipo -create \
    "$build_root/arm64/arm64-apple-macosx/release/CapsLEDMenuBar" \
    "$build_root/x86_64/x86_64-apple-macosx/release/CapsLEDMenuBar" \
    -output "$app_contents/MacOS/CapsLEDMenuBar"
lipo "$app_contents/MacOS/CapsLEDMenuBar" -verify_arch arm64 x86_64

# lipo invalidates signatures from the individual architecture builds. An
# ad-hoc signature restores Mach-O integrity checking, but deliberately does not
# claim Developer ID identity or notarization; the README preserves that limit.
codesign \
    --force \
    --sign - \
    --identifier io.github.sol-momma.capsled \
    "$staging_dir/capsled"
codesign --verify --strict --verbose=2 "$staging_dir/capsled"

# The app is ad-hoc signed for Mach-O integrity for the same reason as the CLI.
# This does not imply Developer ID signing or notarization; distribution docs
# keep that limitation explicit until release credentials are configured.
codesign \
    --force \
    --deep \
    --sign - \
    --identifier io.github.sol-momma.capsled.menubar \
    "$app_dir"
codesign --verify --deep --strict --verbose=2 "$app_dir"

cp "$repository_root/LICENSE" "$staging_dir/LICENSE"
cp "$repository_root/README.md" "$staging_dir/README.md"
cp "$repository_root/README.ja.md" "$staging_dir/README.ja.md"

# Archive from inside staging so installation always finds `capsled` at the
# archive root, independent of the checkout or temporary directory name.
tar -czf "$output_dir/$cli_archive_name" -C "$staging_dir" \
    capsled LICENSE README.md README.ja.md
ditto -c -k --sequesterRsrc --keepParent \
    "$app_dir" \
    "$output_dir/$menu_archive_name"
(
    cd "$output_dir"
    shasum -a 256 "$cli_archive_name" > "$cli_archive_name.sha256"
    shasum -a 256 "$menu_archive_name" > "$menu_archive_name.sha256"
)

echo "Created $output_dir/$cli_archive_name"
echo "Created $output_dir/$cli_archive_name.sha256"
echo "Created $output_dir/$menu_archive_name"
echo "Created $output_dir/$menu_archive_name.sha256"
