#!/usr/bin/env bash

set -euo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
build_root="$repository_root/.build/distribution-build"
output_dir="$repository_root/.build/distribution"
staging_dir="$output_dir/staging"
archive_name="capsled-macos-universal.tar.gz"

# These directories are entirely generated by this script. Clearing only these
# known paths prevents stale slices or checksums from entering a new release,
# while leaving ordinary SwiftPM build products and user files untouched.
rm -rf "$build_root" "$output_dir"
mkdir -p "$staging_dir"

swift build \
    --package-path "$repository_root" \
    --configuration release \
    --arch arm64 \
    --scratch-path "$build_root/arm64"

swift build \
    --package-path "$repository_root" \
    --configuration release \
    --arch x86_64 \
    --scratch-path "$build_root/x86_64"

lipo -create \
    "$build_root/arm64/arm64-apple-macosx/release/capsled" \
    "$build_root/x86_64/x86_64-apple-macosx/release/capsled" \
    -output "$staging_dir/capsled"
lipo "$staging_dir/capsled" -verify_arch arm64 x86_64

# lipo invalidates signatures from the individual architecture builds. An
# ad-hoc signature restores Mach-O integrity checking, but deliberately does not
# claim Developer ID identity or notarization; the README preserves that limit.
codesign \
    --force \
    --sign - \
    --identifier io.github.sol-momma.capsled \
    "$staging_dir/capsled"
codesign --verify --strict --verbose=2 "$staging_dir/capsled"

cp "$repository_root/LICENSE" "$staging_dir/LICENSE"
cp "$repository_root/README.md" "$staging_dir/README.md"
cp "$repository_root/README.ja.md" "$staging_dir/README.ja.md"

# Archive from inside staging so installation always finds `capsled` at the
# archive root, independent of the checkout or temporary directory name.
tar -czf "$output_dir/$archive_name" -C "$staging_dir" \
    capsled LICENSE README.md README.ja.md
(
    cd "$output_dir"
    shasum -a 256 "$archive_name" > "$archive_name.sha256"
)

echo "Created $output_dir/$archive_name"
echo "Created $output_dir/$archive_name.sha256"
